version: '3.7'
services:
  jenkins-server:
    image: jenkins-image
    container_name: jenkins-server
    hostname: jenkins-server
    privileged: true
    restart: always
    user: root
    environment:
      JENKINS_ADMIN_ID: ${JENKINS_ADMIN_ID}
      JENKINS_ADMIN_PASSWORD: ${JENKINS_ADMIN_PASSWORD}
      CASC_JENKINS_CONFIG: "/var/jenkins_home/config-server.yaml"
    ports:
      - 8080:8080
      - 50003:50000
    volumes:
      #- jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      
# volumes:
#     jenkins_data:
#       driver: local

#networks:
#  jenkins-net:      

